CREATE TABLE "telegram_messages" (
	"chat_id" text NOT NULL,
	"chat_type" text NOT NULL,
	"message_id" integer NOT NULL,
	"message_thread_id" integer,
	"is_topic_message" boolean,
	"is_automatic_forward" boolean,
	"from_user_id" bigint,
	"from_first_name" text,
	"from_last_name" text,
	"from_username" text,
	"from_is_bot" boolean DEFAULT false,
	"from_is_premium" boolean,
	"from_language_code" text,
	"sender_chat_id" bigint,
	"sender_chat_username" text,
	"sender_chat_title" text,
	"author_signature" text,
	"text" text,
	"caption" text,
	"media_type" text,
	"entities" jsonb,
	"caption_entities" jsonb,
	"reply_to_message_id" integer,
	"external_reply_chat_id" text,
	"forward_origin_type" text,
	"forward_from_user_id" bigint,
	"forward_from_first_name" text,
	"forward_from_username" text,
	"forward_from_chat_id" bigint,
	"forward_from_chat_title" text,
	"forward_date" timestamp,
	"via_bot_id" bigint,
	"business_connection_id" text,
	"poll_id" text,
	"poll_question" text,
	"edit_date" timestamp,
	"new_chat_member_ids" jsonb,
	"left_chat_member_user_id" bigint,
	"new_chat_title" text,
	"pinned_message_id" integer,
	"date" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"raw" jsonb NOT NULL,
	CONSTRAINT "telegram_messages_chat_id_message_id_pk" PRIMARY KEY("chat_id","message_id")
);
--> statement-breakpoint
CREATE INDEX "telegram_messages_chat_date_idx" ON "telegram_messages" USING btree ("chat_id","date");--> statement-breakpoint
CREATE INDEX "telegram_messages_chat_thread_date_idx" ON "telegram_messages" USING btree ("chat_id","message_thread_id","date");--> statement-breakpoint
CREATE INDEX "telegram_messages_from_user_idx" ON "telegram_messages" USING btree ("from_user_id");--> statement-breakpoint
CREATE INDEX "telegram_messages_chat_type_idx" ON "telegram_messages" USING btree ("chat_type");