/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardProjectsRouteImport } from './routes/_authenticated/dashboard/projects'
import { Route as AuthenticatedDashboardMembersRouteImport } from './routes/_authenticated/dashboard/members'
import { Route as AuthenticatedDashboardInfraRouteImport } from './routes/_authenticated/dashboard/infra'
import { Route as AuthenticatedDashboardFundsRouteImport } from './routes/_authenticated/dashboard/funds'
import { Route as AuthenticatedDashboardEventsRouteImport } from './routes/_authenticated/dashboard/events'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProjectsRoute =
  AuthenticatedDashboardProjectsRouteImport.update({
    id: '/dashboard/projects',
    path: '/dashboard/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardMembersRoute =
  AuthenticatedDashboardMembersRouteImport.update({
    id: '/dashboard/members',
    path: '/dashboard/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardInfraRoute =
  AuthenticatedDashboardInfraRouteImport.update({
    id: '/dashboard/infra',
    path: '/dashboard/infra',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardFundsRoute =
  AuthenticatedDashboardFundsRouteImport.update({
    id: '/dashboard/funds',
    path: '/dashboard/funds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardEventsRoute =
  AuthenticatedDashboardEventsRouteImport.update({
    id: '/dashboard/events',
    path: '/dashboard/events',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/funds': typeof AuthenticatedDashboardFundsRoute
  '/dashboard/infra': typeof AuthenticatedDashboardInfraRoute
  '/dashboard/members': typeof AuthenticatedDashboardMembersRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/funds': typeof AuthenticatedDashboardFundsRoute
  '/dashboard/infra': typeof AuthenticatedDashboardInfraRoute
  '/dashboard/members': typeof AuthenticatedDashboardMembersRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/_authenticated/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/_authenticated/dashboard/funds': typeof AuthenticatedDashboardFundsRoute
  '/_authenticated/dashboard/infra': typeof AuthenticatedDashboardInfraRoute
  '/_authenticated/dashboard/members': typeof AuthenticatedDashboardMembersRoute
  '/_authenticated/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects'
    | '/projects/$id'
    | '/dashboard/events'
    | '/dashboard/funds'
    | '/dashboard/infra'
    | '/dashboard/members'
    | '/dashboard/projects'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects'
    | '/projects/$id'
    | '/dashboard/events'
    | '/dashboard/funds'
    | '/dashboard/infra'
    | '/dashboard/members'
    | '/dashboard/projects'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/projects'
    | '/projects/$id'
    | '/_authenticated/dashboard/events'
    | '/_authenticated/dashboard/funds'
    | '/_authenticated/dashboard/infra'
    | '/_authenticated/dashboard/members'
    | '/_authenticated/dashboard/projects'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/projects': {
      id: '/_authenticated/dashboard/projects'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/members': {
      id: '/_authenticated/dashboard/members'
      path: '/dashboard/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof AuthenticatedDashboardMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/infra': {
      id: '/_authenticated/dashboard/infra'
      path: '/dashboard/infra'
      fullPath: '/dashboard/infra'
      preLoaderRoute: typeof AuthenticatedDashboardInfraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/funds': {
      id: '/_authenticated/dashboard/funds'
      path: '/dashboard/funds'
      fullPath: '/dashboard/funds'
      preLoaderRoute: typeof AuthenticatedDashboardFundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/events': {
      id: '/_authenticated/dashboard/events'
      path: '/dashboard/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof AuthenticatedDashboardEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardEventsRoute: typeof AuthenticatedDashboardEventsRoute
  AuthenticatedDashboardFundsRoute: typeof AuthenticatedDashboardFundsRoute
  AuthenticatedDashboardInfraRoute: typeof AuthenticatedDashboardInfraRoute
  AuthenticatedDashboardMembersRoute: typeof AuthenticatedDashboardMembersRoute
  AuthenticatedDashboardProjectsRoute: typeof AuthenticatedDashboardProjectsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardEventsRoute: AuthenticatedDashboardEventsRoute,
  AuthenticatedDashboardFundsRoute: AuthenticatedDashboardFundsRoute,
  AuthenticatedDashboardInfraRoute: AuthenticatedDashboardInfraRoute,
  AuthenticatedDashboardMembersRoute: AuthenticatedDashboardMembersRoute,
  AuthenticatedDashboardProjectsRoute: AuthenticatedDashboardProjectsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
