import { Elysia } from "elysia";
import { env } from "../env";
import { loginLinkService } from "../services/login-link.service";
import { aiUsageService } from "../services/ai-usage.service";
import { authModel } from "./models/auth";
import { botModel } from "./models/bot";

export const botRoutes = new Elysia({ prefix: "/api/v1/bot" })
  .use(authModel)
  .use(botModel)
  .get(
    "/login",
    async ({ query }) => {
      const response = await loginLinkService.exchangeCode(
        query.code,
        env.WEB_URL,
      );

      if (!response) {
        return new Response(
          "Invalid or expired login link. Please run /login again in the bot.",
          { status: 400, headers: { "Content-Type": "text/plain" } },
        );
      }

      return response;
    },
    {
      query: "auth.loginCodeQuery",
      detail: {
        tags: ["Bot"],
        summary: "One-time bot login",
        description:
          "Exchanges a one-time code for a session cookie and redirects to the web app. Codes are generated by the Telegram bot and expire after 5 minutes.",
      },
    },
  )
  .get("/health", () => ({ status: "ok", bot: "running" }), {
    detail: {
      tags: ["Bot"],
      summary: "Bot health check",
    },
  })
  .get(
    "/usage",
    async ({ query }) => {
      return aiUsageService.getUsageStats({
        from: query.from,
        to: query.to,
        caller: query.caller,
        model: query.model,
      });
    },
    {
      query: "bot.usageQuery",
      detail: {
        tags: ["Bot"],
        summary: "Get AI usage statistics",
        description:
          "Returns aggregated AI SDK usage stats including total tokens, cost estimates, and breakdowns by caller, model, and day.",
      },
    },
  );
