import { Elysia, t } from "elysia";
import { webhookCallback } from "grammy";
import { bot } from "../bot/bot";
import { env } from "../env";
import { loginLinkService } from "../services/login-link.service";

const handleWebhook = webhookCallback(bot, "elysia", {
  secretToken: env.WEBHOOK_SECRET,
});

export const botRoutes = new Elysia({ prefix: "/api/v1/bot" })
  .post(
    "/webhook",
    (ctx) => {
      console.log(
        `[webhook] incoming update:`,
        JSON.stringify(ctx.body, null, 2),
      );
      return handleWebhook(ctx);
    },
    {
      detail: {
        tags: ["Bot"],
        summary: "Telegram webhook callback",
        description:
          "Receives updates from the Telegram Bot API. Authenticated via the X-Telegram-Bot-Api-Secret-Token header.",
      },
    }
  )
  .get(
    "/login",
    async ({ query }) => {
      const response = await loginLinkService.exchangeCode(
        query.code,
        env.WEB_URL,
      );

      if (!response) {
        return new Response(
          "Invalid or expired login link. Please run /register again in the bot.",
          { status: 400, headers: { "Content-Type": "text/plain" } },
        );
      }

      return response;
    },
    {
      query: t.Object({ code: t.String() }),
      detail: {
        tags: ["Bot"],
        summary: "One-time bot login",
        description:
          "Exchanges a one-time code for a session cookie and redirects to the web app. Codes are generated by the Telegram bot and expire after 5 minutes.",
      },
    }
  )
  .get(
    "/health",
    () => ({ status: "ok", bot: "running" }),
    {
      detail: {
        tags: ["Bot"],
        summary: "Bot health check",
      },
    }
  );
